# Generated by Django 3.2.6 on 2021-08-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='slug',
            field=models.CharField(default='none', max_length=100, unique=True),
        ),
    ]
