# Generated by Django 3.2.6 on 2021-08-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0003_alter_url_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='clicks',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
