# Generated by Django 3.2.6 on 2021-08-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urls", "0004_url_clicks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="location",
            field=models.URLField(max_length=2000),
        ),
    ]
