# Generated by Django 3.2.6 on 2021-08-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urls", "0008_fill_shortened_with_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="expiry_date",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
