# Generated by Django 3.2.6 on 2021-08-30 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0012_urltrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urltrack',
            name='when',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
