# Generated by Django 3.2.6 on 2021-08-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urls", "0014_recycleurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="name",
            field=models.CharField(blank=True, default=" ", max_length=50),
        ),
    ]
