name: Build Flutter

on:
  push:
    paths:
      - "mobile/**"

defaults:
  run:
    working-directory: mobile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup the flutter environment
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Upload generated apk to the artifacts
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: mobile/build/app/outputs/apk/release/app-release.apk
